### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by david-curran-90** [microsoft/SDN#283]
docker version

```Client:
 Version:           18.03.1-ee-3
 API version:       1.37
 Go version:        go1.10.2
 Git commit:        b9a5c95
 Built:             Thu Aug 30 18:42:35 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ee-3
  API version:      1.37 (minimum version 1.24)
  Go version:       go1.10.2
  Git commit:       b9a5c95
  Built:            Thu Aug 30 18:56:49 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4",...}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4",...}
```

kubectl config view

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.1.0.6:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

I am running the start.ps1 script with the relevant arguments:

```
.\start.ps1 -ManagementIP 10.1.0.5 -ClusterCIDR 10.244.0.0/16 -ServiceCIDR 10.96.0.0/12 -KubeDnsServiceIP 10.96.0.10
```

Everything seems to start up OK and I see the node as "ready"

dckazunonprod02   Ready      <none>    1d        v1.11.4

However I am getting the invalid memory address error below when waiting for the management IP from cbr0

```
I1128 16:39:37.875119    4976 hostgw_windows.go:164] Waiting to get ManagementIP from HNSNetwork cbr0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10e43ea]

goroutine 1 [running]:
main.main()
        /home/kasubra/repo/gopath/src/github.com/coreos/flannel/main.go:297 +0xbfa
```

This appears to be affecting flanneld as when I run stop.ps1 I don't see flanneld as exiting

```
.\stop.ps1
SUCCESS: The process "kubelet.exe" with PID 184 has been terminated.
SUCCESS: The process "kube-proxy.exe" with PID 7360 has been terminated.
ERROR: The process "flanneld.exe" not found.
```

I am having an issue with resolving service names in the containers built by Kubernetes and think that flanneld.exe not starting correctly may be the issue.

Running flanneld.exe directly starts without errors but does not resolve the issue with service name resolving. Does start.ps1 do something extra to set this up?

```
[Environment]::SetEnvironmentVariable("NODE_NAME", "dckazunonprod02")
C:\flannel\flanneld.exe --kubeconfig-file=C:\k\config --iface=10.1.0.5 --ip-masq=1 --kube-subnet-mgr=1
```
